openapi: 3.1.0
info:
  contact:
    email: talent@kruzhok.org
  description: |-
    Сервис активностей и артефактов игр Берлоги.

    ## v0.5

    - Добавлены административные операции импорта и чтения списка контекстов.

    ## v0.4

    - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).

    ## v0.3
    - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions).
    - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead).
    - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).

    ## v0.2
    [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
  title: Активности Берлоги
  version: "0.5"
servers:
- description: Production Server
  url: https://talent.kruzhok.org/berloga-activities
- description: Development Server
  url: https://talent.test.kruzhok.org/berloga-activities
tags:
- description: "Операции, предназначенные для приложений"
  name: application
- description: "Операции, предназначенные для сервисов"
  name: service
- description: "Операции, предназначенные для администрирования"
  name: admin
paths:
  /activities:
    get:
      description: "Если какие-то из указанных активностей не будут найдены, то он\
        и просто будут отсутствовать в ответе."
      operationId: ActivitiesList
      parameters:
      - description: Идентификаторы активностей
        explode: true
        in: query
        name: ids
        required: true
        schema:
          items:
            format: uuid
            type: string
          maxItems: 50
          minItems: 1
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Activity'
                type: array
          description: OK
      security:
      - BerlogaJWT: []
      summary: Список активностей
      tags:
      - application
    post:
      description: |-
        Каждая из активностей опционально может иметь метрики и артефакт.

        Запись активностей доступна в коротком и расширенном форматах.

        #### Короткий формат

        Передается только массив активностей. Если они ссылаются на артефакты, эти артефакты должны быть предварительно [загружены](#operation/ArtefactsCreate). Ответ на такой запрос тоже включает в себя только массив с активностями.

        #### Расширенный формат

        В этом формате передается объект, который должен содержать активности в массиве, аналогичном короткому формату, и опционально может включать в себя еще артефакты для создания. В ответе на такой запрос, аналогично, возвращается объект, содержащий те же ключи. В возвращаемом массиве артефактов будут ссылки, по которым эти артефакты должны быть загружены.

        > Ссылки имеют ограниченный срок жизни. Если данные артефакта не были загружены в рамках этого периода, то нужно [запросить новую ссылку](#operation/ArtefactUploadURL).

        > До тех пор, пока указанные в активности артефакты не будут загружены, эта активность с ее баллами не будет учитываться в прогрессе традиции игрока.

        После загрузки данных артефакта по полученной ссылке, нужно [подтвердить что загрузка завершена](#operation/ArtefactSetUploaded).
      operationId: ActivitiesCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivitiesCreate_request'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesCreate_201_response'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка валидации данных в запросе
      security:
      - BerlogaJWT: []
      summary: Запись активностей
      tags:
      - application
  /activities/metrics:
    get:
      description: |-
        Обязательно указание либо идентификаторов контекстов `context_ids`,
        либо идентификатора приложения и свойств контекстов `context_property`.
      operationId: ActivitiesMetricsList
      parameters:
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          format: int32
          type: integer
          minumum: 0
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          format: int32
          maximum: 1000
          type: integer
          minumum: 1
        style: form
      - description: ID приложения. Необходимо указывать при использовании фильтра
          `context_property`.
        explode: true
        in: query
        name: application_id
        required: false
        schema:
          description: Идентификатор приложения.
          format: uuid
          type: string
        style: form
      - description: |-
          Свойства контекстов приложения.
          Заполняются в формате имени и значения объединенных пробелом (кодируется как `+` или `%20`).
          На каждое свойство допускается указывать до 5 значений.
          Множественные значения учитываются как `допустим любой из вариантов`,
          или же еще можно сказать что они объединяются логическим ИЛИ.
          В запросе можноственные значения нужно разделять вертикальной чертой.
          Пример фильтра по свойству `instrument` с тремя допустимыми значениями: `instrument+piano|guitar|drums`.
        explode: true
        in: query
        name: context_property
        required: false
        schema:
          items:
            type: string
          maxItems: 3
          minItems: 1
          type: array
        style: form
      - description: Список идентификаторов контекстов.
        explode: true
        in: query
        name: context_ids
        required: false
        schema:
          items:
            $ref: '#/components/schemas/ContextID'
          maxItems: 20
          minItems: 1
          type: array
        style: form
      - explode: true
        in: query
        name: since
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: until
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: "Список игроков, активности которых попадут в выборку."
        explode: true
        in: query
        name: player_ids
        required: false
        schema:
          items:
            $ref: '#/components/schemas/PlayerID'
          maxItems: 50
          minItems: 1
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ActivitiesMetricsList_200_response_inner'
                type: array
          description: OK
          headers:
            X-Count:
              $ref: '#/components/headers/X-Count'
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка доступа
      security:
      - ServiceKey: []
      - TalentOAuth: []
      summary: Список активностей с метриками
      tags:
      - service
  /activities/scores:
    get:
      description: "**Обязательно** указание либо `tradition_id`, либо `context_ids`;\
        \ эти параметры взаимоисключающие."
      operationId: ActivitiesScores
      parameters:
      - description: Идентификатор традиции
        explode: true
        in: query
        name: tradition_id
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Список идентификаторов контекстов
        explode: true
        in: query
        name: context_ids
        required: false
        schema:
          items:
            $ref: '#/components/schemas/ContextID'
          maxItems: 50
          minItems: 1
          type: array
        style: form
      - description: "Список игроков, активности которых попадут в выборку. Параме\
          тр доступен только при использовании авторизации `ServiceKey`."
        explode: true
        in: query
        name: player_ids
        required: false
        schema:
          items:
            $ref: '#/components/schemas/PlayerID'
          maxItems: 50
          minItems: 1
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesScores'
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка доступа
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка в параметрах запроса
      security:
      - BerlogaJWT: []
      - ServiceKey: []
      summary: Балл за активности
      tags:
      - application
      - service
  /activities/scores/traditions:
    get:
      operationId: ActivitiesScoresByTraditions
      parameters:
      - description: Получение баллов по всем PlayerID пользователя
        explode: true
        in: query
        name: talent_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ActivitiesScoresByTraditions_200_response_inner'
                type: array
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка доступа
      security:
      - ServiceKey: []
      summary: Баллы сгруппированные по традициям
      tags:
      - service
  /activities/{activity_id}:
    get:
      operationId: ActivityRead
      parameters:
      - explode: false
        in: path
        name: activity_id
        required: true
        schema:
          $ref: '#/components/schemas/ActivityID'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityRead_200_response'
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Активность не найдена
      security: []
      summary: Чтение активности
      tags:
      - service
  /artefacts:
    post:
      description: Артефакт предварительно загружается для передачи его в активности.
      operationId: ArtefactsCreate
      parameters:
      - description: "ID типа артефакта из [справочника](#operation/ArtefactTypesList)."
        explode: false
        in: header
        name: X-Artefact-Type
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      - description: SHA-1 контрольная сумма
        explode: false
        in: header
        name: X-Checksum
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/*:
            schema:
              format: binary
              type: string
        description: |-
          Содержимое артефакта. Поддерживаемые типы:

            - application/cyberiada-graphml
            - application/json
            - application/xml
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                description: ID артефакта.
                format: uuid
                type: string
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Не найден указанный тип артефакта
      security:
      - BerlogaJWT: []
      summary: Загрузка артефакта
      tags:
      - application
  /artefacts/{artefact_id}/upload-url:
    get:
      description: "Ссылка для загрузки данных артефактом имеет ограниченный срок\
        \ жизни. После его завершения, если данные артефакта еще не были успешно з\
        агружены, нужно запрашивать новую ссылку. Загрузку данных по ссылке нужно\
        \ выполнять методом PUT."
      operationId: ArtefactUploadURL
      parameters:
      - explode: false
        in: path
        name: artefact_id
        required: true
        schema:
          $ref: '#/components/schemas/ArtefactID'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: url
                type: string
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Артефакт не найден
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Данные артефакта уже загружены
      security:
      - BerlogaJWT: []
      summary: Запрос новой ссылки для загрузки
      tags:
      - application
    parameters:
    - explode: false
      in: path
      name: artefact_id
      required: true
      schema:
        $ref: '#/components/schemas/ArtefactID'
      style: simple
  /artefacts/{artefact_id}/set-uploaded:
    parameters:
    - explode: false
      in: path
      name: artefact_id
      required: true
      schema:
        $ref: '#/components/schemas/ArtefactID'
      style: simple
    post:
      operationId: ArtefactSetUploaded
      parameters:
      - explode: false
        in: path
        name: artefact_id
        required: true
        schema:
          $ref: '#/components/schemas/ArtefactID'
        style: simple
      responses:
        "200":
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Артефакт не найден
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Данные артефакта уже загружены
      security:
      - BerlogaJWT: []
      summary: Подтверждение загрузки артефакта
      tags:
      - application
  /artefact-types:
    get:
      operationId: ArtefactTypesList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ArtefactTypesList_200_response_inner'
                type: array
          description: OK
      summary: Справочник типов артефактов
      tags:
      - application
  /contexts:
    get:
      operationId: ContextsList
      parameters:
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          format: int32
          type: integer
          minumum: 0
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          format: int32
          maximum: 100
          type: integer
          minumum: 1
        style: form
      - description: Фильтрация по ID контекстов.
        explode: true
        in: query
        name: id
        required: false
        schema:
          items:
            format: uuid
            type: string
          type: array
        style: form
      - description: Фильтрация по ID традиций.
        explode: true
        in: query
        name: t_id
        required: false
        schema:
          items:
            format: int32
            type: integer
          type: array
        style: form
      - description: Фильтрация по ID приложения.
        explode: true
        in: query
        name: app_id
        required: false
        schema:
          items:
            format: uuid
            type: string
          type: array
        style: form
      - description: Фильтрация по вхождению подстроки в описание контекста.
        explode: true
        in: query
        name: desc
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Context'
                type: array
          description: OK
          headers:
            X-Count:
              $ref: '#/components/headers/X-Count'
        "403":
          $ref: '#/components/responses/Error'
          description: Пользователь не является администратором сервиса
      security:
      - TalentOAuth: []
      summary: Список контекстов
      tags:
      - admin
  /contexts/import:
    post:
      description: |-
        Импортируемая таблица должна содержать колонки `id` и `description`.
        Содержащие в ячейках идентификатор (UUID) и описание контекста соответственно.

        Оставшиеся колонки таблицы будут восприняты как свойства контекстов.
        Тип значения для свойства определяется на основе значений в ячейках колонки.
        Если все значения можно интерпретировать как числовые, то тип значения у свойства будет числовой.
        Если хоть одно значение не приводится к числу, то тип значения определяется как строковый.

        В заголовках запроса так же необходимо указать ID приложения с контекстами которого будет выполнятся работа.
      operationId: ContextsImport
      parameters:
      - description: "ID приложения, для которого импортируются контексты."
        explode: false
        in: header
        name: X-Application
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          text/tsv:
            schema:
              format: binary
              type: string
          text/csv:
            schema:
              format: binary
              type: string
        description: Таблица контекстов для импорта.
        required: true
      responses:
        "201":
          description: Успешно выполнена запись
        "400":
          $ref: '#/components/responses/Error'
          description: Ошибка чтения данных в соответствии с форматом запроса
        "403":
          $ref: '#/components/responses/Error'
          description: Пользователь не является администратором сервиса
        "422":
          content:
            application/json:
              schema:
                description: Строки с ошибками валидации.
                items:
                  $ref: '#/components/schemas/ContextsImport_422_response_inner'
                type: array
          description: Переданы невалидные данные
      security:
      - TalentOAuth: []
      summary: Импорт контекстов со свойствами
      tags:
      - admin
  /contexts/{context_id}/tradition-id:
    get:
      operationId: ContextTraditionID
      parameters:
      - explode: false
        in: path
        name: context_id
        required: true
        schema:
          $ref: '#/components/schemas/ContextID'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                description: ID традиции
                format: int32
                type: integer
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Контекст не найден
      security: []
      summary: Традиция контекста
      tags:
      - service
    parameters:
    - explode: false
      in: path
      name: context_id
      required: true
      schema:
        $ref: '#/components/schemas/ContextID'
      style: simple
components:
  headers:
    X-Count:
      description: "Общее кол-во объектов, входящих в выборку без учета пагинации."
      explode: false
      required: true
      schema:
        format: int64
      style: simple
  responses:
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Ошибка
  schemas:
    Activity:
      description: Сохраненная игровая активность.
      example:
        player_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        app_version: app_version
        scores: 0.8008281904610115
        created_at: 2000-01-23T04:56:07.000+00:00
        context_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        quarantine: missing_artefact
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        artefact_id: ""
      properties:
        id:
          description: Идентификатор активности.
          format: uuid
          type: string
        created_at:
          description: Дата записи активности.
          format: date-time
          type: string
        context_id:
          description: Идентификатор контекста активности.
          format: uuid
          type: string
        player_id:
          description: Идентификатор игрока.
          format: uuid
          type: string
        app_version:
          description: "Версия приложения, в которой была произведена активность."
          type: string
        scores:
          description: Балл эффективности активности.
          format: float64
          type: number
          nullable: true
        artefact_id:
          allOf:
          - $ref: '#/components/schemas/ArtefactID'
          - nullable: true
        quarantine:
          enum:
          - missing_artefact
          - invalid_artefact
          type: string
          nullable: true
      required:
      - app_version
      - artefact_id
      - context_id
      - created_at
      - id
      - player_id
      - quarantine
      - scores
    ActivityID:
      description: Идентификатор активности.
      format: uuid
      type: string
    ActivityScores:
      description: Балл эффективности активности.
      format: float64
      type: number
      nullable: true
    ActivityAppVersion:
      description: "Версия приложения, в которой была произведена активность."
      type: string
    ActivityCreatedAt:
      description: Дата записи активности.
      format: date-time
      type: string
    ActivityWrite:
      description: Записываемая игровая активность.
      properties:
        app_version:
          description: "Версия приложения, в которой была произведена активность."
          type: string
        context_id:
          description: Идентификатор контекста активности.
          format: uuid
          type: string
        artefact_id:
          description: Идентификатор артефакта.
          format: uuid
          type: string
        metrics:
          additionalProperties:
            format: float64
            type: number
          maxProperties: 15
          minProperties: 1
      required:
      - app_version
      - context_id
    ActivityWriteList:
      items:
        $ref: '#/components/schemas/ActivityWrite'
      maxItems: 20
      minItems: 1
      type: array
    ActivityWriteObject:
      properties:
        activities:
          items:
            $ref: '#/components/schemas/ActivityWrite'
          maxItems: 20
          minItems: 1
          type: array
        artefacts:
          items:
            $ref: '#/components/schemas/ActivityWriteObject_artefacts_inner'
          maxItems: 20
          type: array
      required:
      - activities
    ActivitiesCreateList:
      items:
        $ref: '#/components/schemas/ActivitiesCreateList_inner'
      type: array
    ActivitiesCreateObject:
      properties:
        activities:
          items:
            $ref: '#/components/schemas/ActivitiesCreateList_inner'
          type: array
        artefacts:
          items:
            $ref: '#/components/schemas/ActivitiesCreateObject_artefacts_inner'
          type: array
      required:
      - activities
      - artefacts
    ActivityMetrics:
      additionalProperties:
        format: float64
        type: number
      description: Метрики активности.
    ActivitiesScores:
      description: Балл эффективности.
      format: float64
      type: number
    ArtefactID:
      description: Идентификатор артефакта.
      format: uuid
      type: string
    Context:
      description: Контекст активностей
      example:
        activity_type_id: 6
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        application_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tradition_id: 0
      properties:
        id:
          description: Идентификатор контекста активности.
          format: uuid
          type: string
        application_id:
          format: uuid
          type: string
        tradition_id:
          format: int32
          type: integer
        activity_type_id:
          format: int32
          type: integer
        description:
          type: string
      required:
      - activity_type_id
      - application_id
      - description
      - id
      - tradition_id
    ContextID:
      description: Идентификатор контекста активности.
      format: uuid
      type: string
    Error:
      example:
        error_message: error_message
      properties:
        error_message:
          description: Описание ошибки
          type: string
      required:
      - error_message
    PlayerID:
      description: Идентификатор игрока.
      format: uuid
      type: string
    ActivitiesCreate_request:
      oneOf:
      - $ref: '#/components/schemas/ActivityWriteList'
      - $ref: '#/components/schemas/ActivityWriteObject'
    ActivitiesCreate_201_response:
      oneOf:
      - $ref: '#/components/schemas/ActivitiesCreateList'
      - $ref: '#/components/schemas/ActivitiesCreateObject'
    ActivitiesMetricsList_200_response_inner:
      example:
        player_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        app_version: app_version
        activity_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        created_at: 2000-01-23T04:56:07.000+00:00
        context_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        metrics:
          key: 0.8008281904610115
        artefact_id: ""
        context_description: context_description
      properties:
        activity_id:
          description: Идентификатор активности.
          format: uuid
          type: string
        created_at:
          description: Дата записи активности.
          format: date-time
          type: string
        player_id:
          description: Идентификатор игрока.
          format: uuid
          type: string
        app_version:
          description: "Версия приложения, в которой была произведена активность."
          type: string
        context_id:
          description: Идентификатор контекста активности.
          format: uuid
          type: string
        context_description:
          description: Описание контекста
          type: string
        artefact_id:
          allOf:
          - $ref: '#/components/schemas/ArtefactID'
          - nullable: true
        metrics:
          additionalProperties:
            format: float64
            type: number
          description: Метрики активности.
      required:
      - activity_id
      - app_version
      - artefact_id
      - context_description
      - context_id
      - created_at
      - metrics
      - player_id
    ActivitiesScoresByTraditions_200_response_inner:
      example:
        scores: 6.027456183070403
        tradition_id: 0
      properties:
        tradition_id:
          description: ID традиции.
          format: int32
          type: integer
        scores:
          description: Балл эффективности.
          format: float64
          type: number
      required:
      - scores
      - tradition_id
    ActivityRead_200_response_allOf_context_properties_value:
      example:
        value_string: value_string
        value_number: 1.4658129805029452
      properties:
        value_string:
          type: string
          nullable: true
        value_number:
          format: float64
          type: number
          nullable: true
      required:
      - value_number
      - value_string
    ActivityRead_200_response:
      allOf:
      - $ref: '#/components/schemas/Activity'
      - properties:
          application_id:
            description: Идентификатор приложения.
            format: uuid
            type: string
          tradition_id:
            description: ID традиции.
            format: int32
            type: integer
          context_properties:
            additionalProperties:
              $ref: '#/components/schemas/ActivityRead_200_response_allOf_context_properties_value'
            description: Свойства контекста активности.
          metrics:
            $ref: '#/components/schemas/ActivityMetrics'
        required:
        - application_id
        - context_properties
        - metrics
        - tradition_id
      example:
        context_properties:
          key:
            value_string: value_string
            value_number: 1.4658129805029452
        player_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        app_version: app_version
        scores: 0.8008281904610115
        created_at: 2000-01-23T04:56:07.000+00:00
        context_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        quarantine: missing_artefact
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        metrics: null
        artefact_id: ""
        application_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tradition_id: 6
    ArtefactTypesList_200_response_inner:
      example:
        name: name
        id: 0
      properties:
        id:
          description: Идентификатор типа артефактов.
          format: int32
          type: integer
        name:
          description: Название типа артефактов.
          type: string
      required:
      - id
      - name
    ContextsImport_422_response_inner:
      example:
        index: 0
        row:
          key: row
        errors:
        - errors
        - errors
      properties:
        index:
          description: Индекс строки в таблице за исключением строки заголовка.
          type: integer
        row:
          additionalProperties:
            type: string
          description: Данные импортируемые строкой таблицы.
        errors:
          description: Ошибки валидации строки.
          items:
            description: Текст ошибки.
            type: string
          type: array
      required:
      - error
      - index
      - row
    ActivityWriteObject_artefacts_inner:
      properties:
        id:
          description: "ID артефакта, по которому на него ссылаются активности, пе\
            реданные в том же запросе."
          format: uuid
          type: string
        content_type:
          description: MIME-тип артефакта.
          type: string
        artefact_type_id:
          description: "ID типа артефакта из [справочника](#operation/ArtefactTypesList)."
          format: int32
          type: integer
        checksum:
          description: SHA-1 контрольная сумма
          type: string
      required:
      - artefact_type_id
      - checksum
      - content_type
      - id
    ActivitiesCreateList_inner:
      example:
        scores: 0.8008281904610115
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Идентификатор активности.
          format: uuid
          type: string
        scores:
          description: Балл эффективности активности.
          format: float64
          type: number
          nullable: true
      required:
      - id
      - scores
    ActivitiesCreateObject_artefacts_inner:
      properties:
        id:
          description: Идентификатор артефакта.
          format: uuid
          type: string
        upload_url:
          description: Временный URL для загрузки данных артефакта методом PUT
          format: url
          type: string
      required:
      - id
      - upload_url
  securitySchemes:
    BerlogaJWT:
      description: "JWT, полученный эндпоинтом [issue-token](/berloga-idp/docs/#operation/IssueToken)."
      in: header
      name: Authorization
      type: apiKey
    TalentOAuth:
      bearerFormat: JWT
      description: "JWT, полученный OAuth провайдером платформы Талант."
      scheme: bearer
      type: http
    ServiceKey:
      in: header
      name: X-Service-Key
      type: apiKey

